=== jonanFan/RRT/Red/Route.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT routes (route+)>
<!ELEMENT route (gateway+)>
<!ATTLIST route
	start NMTOKEN #REQUIRED
	stop NMTOKEN #REQUIRED	
>
<!ELEMENT gateway EMPTY>
<!ATTLIST gateway
	id NMTOKEN #REQUIRED
	prob NMTOKEN "1"
>

=== jonanFan/RRT/router2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE routes SYSTEM "Red/Route.dtd" > 

<routes>
	<route start="1" stop="1">
		<gateway id="0" prob="1"/>
	</route>
	<route start="5" stop="5">
		<gateway id="1" prob="1"/>
	</route>
	<route start="3" stop="4">
		<gateway id="2" prob="0.67"/>
		<gateway id="3" prob="0.33"/>
	</route>
</routes>
